version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./server.conf:/etc/nginx/conf.d/server.conf
      - ./code:/etc/nginx/sites-available
      - ./code:/etc/nginx/sites-enabled
    depends_on:
      - php
    networks:
      - webnet

  php:
    image: php:7.4-fpm
    volumes:
      - ./code:/etc/nginx/sites-available
      - ./code:/etc/nginx/sites-enabled
    networks:
      - webnet

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: strong_and_secure_password
      MYSQL_DATABASE: website_database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webnet

networks:
  webnet:

volumes:
  db_data:
